### ISSUE TITLE
Add support for SkyDrop

### ISSUE THREAD

**Issue by fhorinek** [leonardoxc/leonardoxc#57]
Hello I am the developer for SkyBean and SkyDrop vario (http://skybean.eu/)

I would like to ask you to add support for our vali program.
It is already approved by FAI-civil open validation server.

the approved vali binary can be found here
https://github.com/arieck/vali2/blob/master/cgi-bin/vali-xsb.exe?raw=true
(I can also provide you with linux binary)

If you have any other conditions please feel free to contact me.

Fero

**Comment by leonardoxc** [comment]
Hi Fero,
    
    sure will add it  next week and give you and update
    
    I am using your SkyBean vario for my winter flights and love it 
    SkyDrop seems also really cool but i am afraid the readings will be
    too small for my eyes :-(
    
    Please consider  that there quite a few pilots with short sight ,
    maybe an instrument with bigger readings ?
    
    Cheers,
    Manolis
    Manolis Andreadakis
Skype: m.andreadakis
Mob: +30 6947262249
    On 16/2/2016 10:29 πμ, František
      Horínek wrote:
    
    
      Hello I am the developer for SkyBean and SkyDrop vario (http://skybean.eu/)
      I would like to ask you to add support for our vali program.
        It is already approved by FAI-civil open validation server.
      the approved vali binary can be found here
        https://github.com/arieck/vali2/blob/master/cgi-bin/vali-xsb.exe?raw=true
        (I can also provide you with linux binary)
      If you have any other conditions please feel free to contact
        me.
      Fero
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by fhorinek** [comment]
Great to hear that!

Regarding the skydrop. We are now testing theese raiser mounts https://www.facebook.com/varioskybean/photos/pcb.540704529428791/540703356095575/?type=3&theater

or you can customise the screen to display only one big number :-)

Next device will be bigger, but there is still lot of work to do.

**Comment by leonardoxc** [comment]
can you please provide a valid IGC that passes validation with your vali prog ?

**Comment by fhorinek** [comment]
you can use this
https://github.com/arieck/vali2/blob/master/sample-igc/sample-xsb.igc

**Comment by leonardoxc** [comment]
vali added

**Comment by fhorinek** [comment]
Thank you!
