### ISSUE TITLE
Unable to access Leonardo after install - missing database table ?

### ISSUE THREAD

**Issue by tmo-github** [leonardoxc/leonardoxc#59]
I am trying to install Leonardo, having cloned the repository yesterday, and having followed the installation instructions on the website.
When I first try to access the URL of my install, I am greeted with an error message which says : 

**Error in query: SELECT * FROM leonardo_friends WHERE userID=0**

There does not seem to be any **leonardo_friends** table in any of the SQL files to be used to populate initially the database. I have scanned through the various subdirectories and haven't found anything related to a table called leonardo_friends, but maybe I have missed it.

I suspect the SQL statement to create that table was inadvertently omitted from the *.sql file. Is it possible to get it fixed ? Thanks.

As noted by someone else in a previous issue, the support forums seem to be broken. It is currently not possible to create an account. If the idea is to get us to interact here on github, I would suggest to formally switch the old forum to read-only to preserve the archives, remove the screen to allow for the creation of accounts and put a notification about it, pointing at Github.

**Comment by leonardoxc** [comment]
just committed the table.

indeed forum is dead, and cannot give much support to the project due to limited available time.

**Comment by tmo-github** [comment]
Thanks for the quick reply. Works fine with the committed SQL statement for the table creation.
