### ISSUE TITLE
API for IGC uploading

### ISSUE THREAD

**Issue by yuri-vin** [leonardoxc/leonardoxc#69]
Hello guys,

Is there an API that would allow for submitting a flight by uploading the IGC file? If not, any plans for this? Thanks!

**Comment by robertgrubba** [comment]
You can upload files by sending POST request, check Leonardo docs folder.

Best regards,
Robert Grubba
HTTPS://leonardo.pgxc.pl




wt., 21.05.2019, 16:15 użytkownik yuri-vin <notifications@github.com>
napisał:

**Comment by yuri-vin** [comment]
Thanks a lot! 
My bad, didn't notice that folder. Found the info in the doc/direct_upload.html file :)
